TARGET=	libdev.a
TYPE=	LIBRARY
OBJS=	drvlib_init.o \
	queue.o assert.o atol.o \
	htonl.o htons.o ntohl.o ntohs.o \
	strncpy.o strlcpy.o strncmp.o strnlen.o memcpy.o memset.o \
	delay.o

include $(SRCDIR)/mk/dev.mk
