TARGET=		platform.o
TYPE=		OBJECT
OBJS=		../arm/locore.o locore_gba.o ../arm/cpufunc.o \
		interrupt.o ../arm/context.o ../arm/trap.o ../arm/cpu.o \
		machdep.o clock.o diag.o

include $(SRCDIR)/mk/sys.mk
