
include $(SRCDIR)/usr/lib/posix/signal/Makefile.inc
include $(SRCDIR)/usr/lib/posix/process/Makefile.inc
include $(SRCDIR)/usr/lib/posix/file/Makefile.inc
include $(SRCDIR)/usr/lib/posix/exec/Makefile.inc
include $(SRCDIR)/usr/lib/posix/gen/Makefile.inc
include $(SRCDIR)/usr/lib/posix/time/Makefile.inc
