LIB=	$(SRCDIR)/usr/lib/libc.a

include $(SRCDIR)/mk/own.mk

include $(SRCDIR)/usr/lib/prex/Makefile.inc
include $(SRCDIR)/usr/lib/posix/Makefile.inc
include $(SRCDIR)/usr/lib/libc/ctype/Makefile.inc
include $(SRCDIR)/usr/lib/libc/errno/Makefile.inc
include $(SRCDIR)/usr/lib/libc/gen/Makefile.inc
include $(SRCDIR)/usr/lib/libc/stdio/Makefile.inc
include $(SRCDIR)/usr/lib/libc/stdlib/Makefile.inc
include $(SRCDIR)/usr/lib/libc/string/Makefile.inc
include $(SRCDIR)/usr/lib/libc/termios/Makefile.inc
include $(SRCDIR)/usr/lib/libc/time/Makefile.inc

include $(SRCDIR)/mk/lib.mk
