VPATH:=	$(SRCDIR)/usr/lib/libc/ctype:$(VPATH)

SRCS+=	isalnum.c isalpha.c iscntrl.c isdigit.c isgraph.c islower.c \
	isprint.c ispunct.c isspace.c isupper.c isxdigit.c isblank.c \
	tolower.c toupper.c
